/**
 * Tradução EN→PT para exibir o figurino aplicado abaixo de cada retrato gerado.
 * Dicionário inverso simples baseado em PT_EN_FASHION (portraitPrompts.ts).
 *
 * Estratégia: substituições por substring case-insensitive na ordem mais
 * específico → mais genérico. Termos não mapeados ficam em inglês — preferimos
 * preservar fidelidade a inventar tradução.
 */

const EN_PT_FASHION: Array<[RegExp, string]> = [
  // Vestidos
  [/\bmidi sheath dress\b/gi, "vestido tubinho midi"],
  [/\bsheath dress\b/gi, "vestido tubinho"],
  [/\bmidi dress\b/gi, "vestido midi"],
  [/\blong dress\b/gi, "vestido longo"],
  [/\bwrap dress\b/gi, "vestido envelope"],
  [/\bshirt dress\b/gi, "vestido camisa"],
  [/\bslip dress\b/gi, "vestido slip"],
  [/\bdress\b/gi, "vestido"],
  // Casacos
  [/\bovercoat\b/gi, "sobretudo"],
  [/\btrench coat\b/gi, "trench coat"],
  [/\blong coat\b/gi, "casaco longo"],
  [/\bleather jacket\b/gi, "jaqueta de couro"],
  [/\bcoat\b/gi, "casaco"],
  [/\bjacket\b/gi, "jaqueta"],
  // Blazers
  [/\btailored blazer\b/gi, "blazer alfaiataria"],
  [/\bstructured blazer\b/gi, "blazer estruturado"],
  [/\boversized blazer\b/gi, "blazer oversized"],
  [/\bdouble-breasted blazer\b/gi, "blazer transpassado"],
  [/\btuxedo-style blazer\b/gi, "blazer smoking"],
  [/\bblazer\b/gi, "blazer"],
  [/\bpantsuit\b/gi, "terninho"],
  [/\bthree-piece suit\b/gi, "terno de 3 peças"],
  [/\bpinstripe suit\b/gi, "terno risca-de-giz"],
  [/\bsuit\b/gi, "terno"],
  // Calças
  [/\btailored trousers\b/gi, "calça alfaiataria"],
  [/\bwide-leg trousers\b/gi, "calça pantalona"],
  [/\bwide-leg pants\b/gi, "calça pantalona"],
  [/\bstraight-leg trousers\b/gi, "calça reta"],
  [/\bstraight-leg jeans\b/gi, "jeans reto"],
  [/\bdenim jeans\b/gi, "jeans"],
  [/\bhigh-waist\b/gi, "cintura alta"],
  [/\bchinos\b/gi, "calça chino"],
  [/\btrousers\b/gi, "calça"],
  [/\bpants\b/gi, "calça"],
  [/\bjumpsuit\b/gi, "macacão"],
  // Tops
  [/\bsilk shell\b/gi, "blusa de seda"],
  [/\bsilk shirt\b/gi, "camisa de seda"],
  [/\bsilk blouse\b/gi, "blusa de seda"],
  [/\bsilk camisole\b/gi, "regata de seda"],
  [/\bsilk top\b/gi, "top de seda"],
  [/\bsilk button-up\b/gi, "camisa de seda"],
  [/\bbutton-up shirt\b/gi, "camisa social"],
  [/\bbutton-up\b/gi, "camisa social"],
  [/\bcotton blouse\b/gi, "blusa de algodão"],
  [/\blinen blouse\b/gi, "blusa de linho"],
  [/\blinen shirt\b/gi, "camisa de linho"],
  [/\bpoplin shirt\b/gi, "camisa de tricoline"],
  [/\bcashmere top\b/gi, "blusa de cashmere"],
  [/\bcashmere sweater\b/gi, "suéter de cashmere"],
  [/\bcashmere t-shirt\b/gi, "camiseta de cashmere"],
  [/\bcashmere turtleneck\b/gi, "gola alta de cashmere"],
  [/\bmerino sweater\b/gi, "suéter de merino"],
  [/\bknit top\b/gi, "top de tricô"],
  [/\bknit sweater\b/gi, "suéter de tricô"],
  [/\bknit cardigan\b/gi, "cardigã de tricô"],
  [/\bknitwear\b/gi, "tricô"],
  [/\bcardigan\b/gi, "cardigã"],
  [/\bturtleneck\b/gi, "gola alta"],
  [/\bhenley top\b/gi, "henley"],
  [/\bsweater\b/gi, "suéter"],
  [/\bsatin blouse\b/gi, "blusa de cetim"],
  [/\bvelvet blazer\b/gi, "blazer de veludo"],
  [/\bwrap top\b/gi, "blusa transpassada"],
  [/\bblouse\b/gi, "blusa"],
  [/\bshirt\b/gi, "camisa"],
  [/\bcamisole\b/gi, "regata"],
  [/\btank top\b/gi, "regata"],
  [/\bt-shirt\b/gi, "camiseta"],
  // Acessórios
  [/\bleather belt\b/gi, "cinto de couro"],
  [/\bgold belt\b/gi, "cinto dourado"],
  [/\bbelt\b/gi, "cinto"],
  [/\bpearl earrings\b/gi, "brincos de pérola"],
  [/\bgold hoop earrings\b/gi, "brincos de argola dourados"],
  [/\bgold studs?\b/gi, "brincos dourados"],
  [/\bsilver hoops\b/gi, "argolas prata"],
  [/\bsilver studs?\b/gi, "brincos prata"],
  [/\bstatement earrings\b/gi, "brincos statement"],
  [/\bsculptural earrings\b/gi, "brincos esculturais"],
  [/\bmother-of-pearl earrings\b/gi, "brincos de madrepérola"],
  [/\bpearl studs\b/gi, "brincos de pérola"],
  [/\bearrings\b/gi, "brincos"],
  [/\bgold necklace\b/gi, "colar dourado"],
  [/\bgold chain\b/gi, "corrente dourada"],
  [/\bgold pendant\b/gi, "pingente dourado"],
  [/\blayered gold necklaces?\b/gi, "colares dourados sobrepostos"],
  [/\bnecklace\b/gi, "colar"],
  [/\bsilver watch\b/gi, "relógio prata"],
  [/\bgold watch\b/gi, "relógio dourado"],
  [/\bleather watch\b/gi, "relógio de couro"],
  [/\bleather strap watch\b/gi, "relógio com pulseira de couro"],
  [/\bleather wristwatch\b/gi, "relógio de pulso de couro"],
  [/\bwatch\b/gi, "relógio"],
  [/\bsignet ring\b/gi, "anel signet"],
  [/\bstacked gold rings\b/gi, "anéis dourados sobrepostos"],
  [/\bgold cuff bracelet\b/gi, "bracelete dourado"],
  [/\bgold cuff\b/gi, "bracelete dourado"],
  [/\bring\b/gi, "anel"],
  [/\bpocket square\b/gi, "lenço de bolso"],
  [/\bscarf\b/gi, "lenço"],
  // Cabelo / posture (casos comuns nos pools)
  [/\bsleek hair tucked\b/gi, "cabelo liso preso"],
  [/\bsleek hair\b/gi, "cabelo liso"],
  [/\bglossy hair\b/gi, "cabelo brilhante"],
  [/\bnatural hair texture\b/gi, "textura natural do cabelo"],
  [/\bsoft hair waves\b/gi, "ondas suaves no cabelo"],
  [/\bhair softly waved\b/gi, "cabelo com ondas suaves"],
  [/\bhair tied back\b/gi, "cabelo preso"],
  [/\bgentle posture\b/gi, "postura suave"],
  [/\bhalf-tucked\b/gi, "meio por dentro"],
  [/\btied at the waist\b/gi, "amarrada na cintura"],
  [/\bover\b/gi, "sobre"],
  [/\bunder\b/gi, "sob"],
  [/\bwith\b/gi, "com"],
  [/\bin\b/gi, "em"],
  [/\band\b/gi, "e"],
  // Cores
  [/\bnavy\b/gi, "azul-marinho"],
  [/\bmidnight blue\b/gi, "azul meia-noite"],
  [/\bdeep navy\b/gi, "azul-marinho profundo"],
  [/\bcharcoal\b/gi, "grafite"],
  [/\bgraphite grey\b/gi, "cinza grafite"],
  [/\bgraphite\b/gi, "grafite"],
  [/\bdeep burgundy\b/gi, "bordô profundo"],
  [/\bburgundy\b/gi, "bordô"],
  [/\bplum\b/gi, "ameixa"],
  [/\bdeep plum\b/gi, "ameixa profundo"],
  [/\bemerald\b/gi, "esmeralda"],
  [/\bdeep emerald\b/gi, "esmeralda profundo"],
  [/\bforest green\b/gi, "verde-floresta"],
  [/\bsage green\b/gi, "verde-sálvia"],
  [/\bsage\b/gi, "verde-sálvia"],
  [/\bolive\b/gi, "oliva"],
  [/\bcamel\b/gi, "camelo"],
  [/\bcaramel\b/gi, "caramelo"],
  [/\btaupe\b/gi, "taupe"],
  [/\bbeige\b/gi, "bege"],
  [/\bivory\b/gi, "marfim"],
  [/\bcream\b/gi, "creme"],
  [/\boff-white\b/gi, "off-white"],
  [/\bchampagne\b/gi, "champanhe"],
  [/\bblush pink\b/gi, "rosa blush"],
  [/\bdusty rose\b/gi, "rosa antigo"],
  [/\bsoft rose\b/gi, "rosa suave"],
  [/\bdeep rose\b/gi, "rosa profundo"],
  [/\brose\b/gi, "rosa"],
  [/\bmauve\b/gi, "malva"],
  [/\blavender\b/gi, "lavanda"],
  [/\bterracotta\b/gi, "terracota"],
  [/\brust\b/gi, "ferrugem"],
  [/\bburnt orange\b/gi, "laranja queimado"],
  [/\bmustard\b/gi, "mostarda"],
  [/\bnude\b/gi, "nude"],
  [/\btan\b/gi, "caqui claro"],
  [/\bbrown\b/gi, "marrom"],
  [/\bwarm brown\b/gi, "marrom quente"],
  [/\bblack\b/gi, "preto"],
  [/\bink black\b/gi, "preto"],
  [/\bwhite\b/gi, "branco"],
  [/\bgrey\b/gi, "cinza"],
  [/\bstone grey\b/gi, "cinza pedra"],
  [/\bmid-grey\b/gi, "cinza médio"],
  [/\bdark indigo\b/gi, "índigo escuro"],
  [/\bindigo\b/gi, "índigo"],
  [/\bgold\b/gi, "dourado"],
  [/\bsilver\b/gi, "prata"],
];

export function enToPtFashion(text: string): string {
  if (!text) return "";
  let out = text;
  for (const [re, pt] of EN_PT_FASHION) {
    out = out.replace(re, pt);
  }
  // Limpeza leve
  out = out.replace(/\s{2,}/g, " ").replace(/\s,/g, ",").trim();
  // Capitaliza primeira letra
  return out.charAt(0).toUpperCase() + out.slice(1);
}
