// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/get-latest-report.ts
import { createClient } from "npm:@supabase/supabase-js@^2.105.4";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_latest_report_default = defineTool({
  name: "get_latest_report",
  title: "Get latest strategic report",
  description: "Return the most recent (highest version) strategic report for the signed-in Posiciona user, including archetype analysis and narrative content.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("reports").select("id, version, status, content, created_at, updated_at").eq("user_id", ctx.getUserId()).order("version", { ascending: false }).limit(1).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "No report found for this user yet." }] };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { report: data }
    };
  }
});

// src/lib/mcp/tools/get-editorial-week.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.105.4";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_editorial_week_default = defineTool2({
  name: "get_editorial_week",
  title: "Get editorial week",
  description: "Return the content of a single editorial week (7 days of posts) from the signed-in user's latest strategic report. Omit weekIndex to get the most recent week.",
  inputSchema: {
    weekIndex: z.number().int().min(0).optional().describe("Zero-based index of the week to fetch. Omit for the latest week.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ weekIndex }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser2(ctx);
    const { data, error } = await supabase.from("reports").select("editorial_weeks").eq("user_id", ctx.getUserId()).order("version", { ascending: false }).limit(1).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const weeks = data?.editorial_weeks ?? [];
    if (!weeks.length) {
      return { content: [{ type: "text", text: "No editorial weeks generated yet." }] };
    }
    const idx = typeof weekIndex === "number" ? weekIndex : weeks.length - 1;
    if (idx < 0 || idx >= weeks.length) {
      return {
        content: [{ type: "text", text: `weekIndex out of range. Available: 0..${weeks.length - 1}` }],
        isError: true
      };
    }
    const week = weeks[idx];
    return {
      content: [{ type: "text", text: JSON.stringify(week) }],
      structuredContent: { weekIndex: idx, totalWeeks: weeks.length, week }
    };
  }
});

// src/lib/mcp/tools/get-credit-balance.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.105.4";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_credit_balance_default = defineTool3({
  name: "get_credit_balance",
  title: "Get credit balance",
  description: "Return the signed-in user's current Posiciona credit balance: weekly cycles, reanalysis, portraits, and regeneration credits.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser3(ctx);
    const { data, error } = await supabase.from("user_balances").select(
      "weekly_cycles, reanalysis_credits, portrait_credits_included, portrait_credits_extra, regeneration_credits, updated_at"
    ).eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "No balance record found." }] };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { balance: data }
    };
  }
});

// src/lib/mcp/tools/list-portraits.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.105.4";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_portraits_default = defineTool4({
  name: "list_portraits",
  title: "List recent brand portraits",
  description: "List the signed-in user's most recent brand portrait generations with status and timestamps.",
  inputSchema: {
    limit: z2.number().int().min(1).max(50).optional().describe("Max entries to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser4(ctx);
    const { data, error } = await supabase.from("portrait_generations").select("id, status, style_index, engine, created_at, completed_at, kept_indices").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { portraits: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "opmheegtmdjqwrfkdboq";
var mcp_default = defineMcp({
  name: "posiciona-mcp",
  title: "Posiciona MCP",
  version: "0.1.0",
  instructions: "Ferramentas do Posiciona (posicionamento de marca pessoal). Use get_latest_report para o relat\xF3rio estrat\xE9gico mais recente do usu\xE1rio, get_editorial_week para conte\xFAdo semanal, get_credit_balance para saldo de cr\xE9ditos, e list_portraits para retratos de marca gerados.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_latest_report_default, get_editorial_week_default, get_credit_balance_default, list_portraits_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
