
UPDATE public.archetype_questions SET statement = 'Presumo que as pessoas que conheço são confiáveis.' WHERE question_number = 1;
UPDATE public.archetype_questions SET statement = 'Me preocupo com o quanto fui ferido(a) na infância.' WHERE question_number = 2;
UPDATE public.archetype_questions SET statement = 'A competição me energiza.' WHERE question_number = 3;
UPDATE public.archetype_questions SET statement = 'Acredito que as pessoas não têm a intenção real de ferir umas às outras.' WHERE question_number = 4;
UPDATE public.archetype_questions SET statement = 'Aprendi que é importante não esperar demais.' WHERE question_number = 5;
UPDATE public.archetype_questions SET statement = 'Estou disposto(a) a correr riscos pessoais para defender minhas crenças.' WHERE question_number = 6;
UPDATE public.archetype_questions SET statement = 'Posso contar com os outros para cuidarem de mim.' WHERE question_number = 7;
UPDATE public.archetype_questions SET statement = 'As pessoas em quem confio me decepcionam.' WHERE question_number = 8;
UPDATE public.archetype_questions SET statement = 'Deixo o medo de lado e faço o que precisa ser feito.' WHERE question_number = 9;
UPDATE public.archetype_questions SET statement = 'Eu me sinto seguro(a).' WHERE question_number = 10;
UPDATE public.archetype_questions SET statement = 'Os outros se aproveitam de mim.' WHERE question_number = 11;
UPDATE public.archetype_questions SET statement = 'Enfrento pessoas ofensivas.' WHERE question_number = 12;
UPDATE public.archetype_questions SET statement = 'Sei que minhas necessidades serão atendidas.' WHERE question_number = 13;
UPDATE public.archetype_questions SET statement = 'Me sinto sobrecarregado(a) pelas circunstâncias.' WHERE question_number = 14;
UPDATE public.archetype_questions SET statement = 'Me sinto à vontade sendo assertivo(a).' WHERE question_number = 15;
UPDATE public.archetype_questions SET statement = 'O mundo é um lugar seguro.' WHERE question_number = 16;
UPDATE public.archetype_questions SET statement = 'Acho difícil me motivar.' WHERE question_number = 17;
UPDATE public.archetype_questions SET statement = 'A competição traz à tona meus melhores esforços.' WHERE question_number = 18;
UPDATE public.archetype_questions SET statement = 'Encontro realização ao doar aos outros.' WHERE question_number = 19;
UPDATE public.archetype_questions SET statement = 'Estou em busca de novos e melhores caminhos.' WHERE question_number = 20;
UPDATE public.archetype_questions SET statement = 'Sinto amor pelas pessoas em geral.' WHERE question_number = 21;
UPDATE public.archetype_questions SET statement = 'Acho mais fácil fazer pelos outros do que por mim mesmo(a).' WHERE question_number = 22;
UPDATE public.archetype_questions SET statement = 'Estou buscando maneiras de me aprimorar.' WHERE question_number = 23;
UPDATE public.archetype_questions SET statement = 'Encontro realização através dos relacionamentos.' WHERE question_number = 24;
UPDATE public.archetype_questions SET statement = 'Sinto satisfação ao cuidar dos outros.' WHERE question_number = 25;
UPDATE public.archetype_questions SET statement = 'Sinto-me inquieto(a).' WHERE question_number = 26;
UPDATE public.archetype_questions SET statement = 'Gosto de ajudar as pessoas a se conectarem umas com as outras.' WHERE question_number = 27;
UPDATE public.archetype_questions SET statement = 'Tenho dificuldade em dizer não.' WHERE question_number = 28;
UPDATE public.archetype_questions SET statement = 'Estou esperando por algo melhor.' WHERE question_number = 29;
UPDATE public.archetype_questions SET statement = 'A intimidade é uma prioridade para mim.' WHERE question_number = 30;
UPDATE public.archetype_questions SET statement = 'Coloco as necessidades dos outros antes das minhas.' WHERE question_number = 31;
UPDATE public.archetype_questions SET statement = 'Estou explorando novas possibilidades.' WHERE question_number = 32;
UPDATE public.archetype_questions SET statement = 'Sou romântico(a).' WHERE question_number = 33;
UPDATE public.archetype_questions SET statement = 'A gentileza é um valor fundamental para mim.' WHERE question_number = 34;
UPDATE public.archetype_questions SET statement = 'Não me conformo com os padrões.' WHERE question_number = 35;
UPDATE public.archetype_questions SET statement = 'Sinto-me mais completo(a) quando estou apaixonado(a).' WHERE question_number = 36;
UPDATE public.archetype_questions SET statement = 'Estou saindo de uma situação ruim.' WHERE question_number = 37;
UPDATE public.archetype_questions SET statement = 'Estou criando minha própria vida.' WHERE question_number = 38;
UPDATE public.archetype_questions SET statement = 'Sou bom(a) em combinar as habilidades das pessoas com as tarefas que precisam ser feitas.' WHERE question_number = 39;
UPDATE public.archetype_questions SET statement = 'Minha vida está mudando rapidamente.' WHERE question_number = 40;
UPDATE public.archetype_questions SET statement = 'Tenho muito mais ideias ótimas do que tempo para colocá-las em prática.' WHERE question_number = 41;
UPDATE public.archetype_questions SET statement = 'Tenho qualidades de liderança.' WHERE question_number = 42;
UPDATE public.archetype_questions SET statement = 'Existe um vazio na minha vida.' WHERE question_number = 43;
UPDATE public.archetype_questions SET statement = 'Tenho momentos de grandes conquistas que parecem acontecer sem esforço.' WHERE question_number = 44;
UPDATE public.archetype_questions SET statement = 'Prefiro estar no controle.' WHERE question_number = 45;
UPDATE public.archetype_questions SET statement = 'Sinto-me confuso(a) com tantas mudanças na minha vida.' WHERE question_number = 46;
UPDATE public.archetype_questions SET statement = 'A inspiração vem facilmente para mim.' WHERE question_number = 47;
UPDATE public.archetype_questions SET statement = 'Prefiro estar no comando.' WHERE question_number = 48;
UPDATE public.archetype_questions SET statement = 'Experiências recentes me fizeram repensar quem eu sou.' WHERE question_number = 49;
UPDATE public.archetype_questions SET statement = 'As pessoas me veem como uma pessoa criativa.' WHERE question_number = 50;
UPDATE public.archetype_questions SET statement = 'Eu assumo o controle se as coisas parecem estar saindo do controle.' WHERE question_number = 51;
UPDATE public.archetype_questions SET statement = 'Estou de luto por uma perda.' WHERE question_number = 52;
UPDATE public.archetype_questions SET statement = 'Tenho uma boa imaginação.' WHERE question_number = 53;
UPDATE public.archetype_questions SET statement = 'Tenho o dever de cumprir minhas obrigações.' WHERE question_number = 54;
UPDATE public.archetype_questions SET statement = 'Mudar meus pensamentos internos muda minha vida externa.' WHERE question_number = 55;
UPDATE public.archetype_questions SET statement = 'Acredito que há muitas formas válidas de enxergar a mesma coisa.' WHERE question_number = 56;
UPDATE public.archetype_questions SET statement = 'Gosto de fazer as pessoas rirem.' WHERE question_number = 57;
UPDATE public.archetype_questions SET statement = 'Acredito que todas as pessoas e coisas do mundo estão interconectadas.' WHERE question_number = 58;
UPDATE public.archetype_questions SET statement = 'Busco ser objetivo(a).' WHERE question_number = 59;
UPDATE public.archetype_questions SET statement = 'Gosto de animar pessoas que são sérias demais.' WHERE question_number = 60;
UPDATE public.archetype_questions SET statement = 'Gosto de transformar situações.' WHERE question_number = 61;
UPDATE public.archetype_questions SET statement = 'Penso de forma profunda.' WHERE question_number = 62;
UPDATE public.archetype_questions SET statement = 'Os outros me veem como divertido(a).' WHERE question_number = 63;
UPDATE public.archetype_questions SET statement = 'Minha presença costuma ser um catalisador de mudanças.' WHERE question_number = 64;
UPDATE public.archetype_questions SET statement = 'Tento encontrar verdades por trás das ilusões.' WHERE question_number = 65;
UPDATE public.archetype_questions SET statement = 'Dou risada da absurdez da vida.' WHERE question_number = 66;
UPDATE public.archetype_questions SET statement = 'A ajuda espiritual explica minha eficácia.' WHERE question_number = 67;
UPDATE public.archetype_questions SET statement = 'Outras pessoas procuram meus conselhos.' WHERE question_number = 68;
UPDATE public.archetype_questions SET statement = 'Brinco bastante.' WHERE question_number = 69;
UPDATE public.archetype_questions SET statement = 'O processo da minha própria cura me permite ajudar a curar os outros.' WHERE question_number = 70;
UPDATE public.archetype_questions SET statement = 'Gosto de desafios que realmente me fazem pensar.' WHERE question_number = 71;
UPDATE public.archetype_questions SET statement = 'Não há nada melhor do que uma boa risada.' WHERE question_number = 72;
