// This file is automatically generated. Do not edit it directly.
import { createClient, processLock } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // Use the in-process lock instead of the Web Locks API. The browser
    // navigator.locks can stay orphaned across tab switches / HMR in the
    // Lovable Preview, freezing signInWithPassword before the request fires.
    lock: processLock,
  },
});
